"""Danish sentiment and emotion lexicons.

Sentiment scores based on AFINN (Finn Årup Nielsen, public domain).
Emotion lexicon based on NRC-style categories mapped to Danish financial/general vocabulary.

Emotion categories (Plutchik's wheel):
  joy, trust, anticipation, surprise, fear, sadness, anger, disgust
"""

# AFINN-da: Danish sentiment word list (subset focused on finance/news/podcast context)
# Scores range from -5 (most negative) to +5 (most positive)
AFINN_DA: dict[str, int] = {
    # Positive words
    "fantastisk": 4, "fremragende": 4, "enestående": 4, "vidunderlig": 4,
    "strålende": 4, "suveræn": 4, "exceptionel": 4, "perfekt": 4,
    "god": 3, "godt": 3, "gode": 3, "bedste": 4, "bedre": 2,
    "positiv": 2, "positivt": 2, "positive": 2,
    "stærk": 2, "stærkt": 2, "styrke": 2, "styrket": 2,
    "vækst": 2, "vokser": 2, "vokset": 2, "fremgang": 3,
    "stigning": 2, "stiger": 2, "steget": 2, "stigende": 2,
    "rekord": 3, "rekordstort": 3, "rekordhøj": 3, "rekordhøjt": 3,
    "succes": 3, "succesfuld": 3, "triumf": 3,
    "optimisme": 3, "optimistisk": 3, "optimistiske": 3,
    "chance": 2, "mulighed": 2, "muligheder": 2, "potentiale": 2,
    "gevinst": 2, "afkast": 1, "profit": 2, "overskud": 2,
    "udbytte": 1, "bonus": 2, "fordel": 2, "fordele": 2,
    "optur": 3, "boom": 3, "rally": 3, "bullish": 2,
    "sikker": 2, "sikkert": 2, "sikkerhed": 2, "stabil": 2, "stabilitet": 2,
    "tillid": 2, "troværdig": 2, "solid": 2, "robust": 2,
    "imponerende": 3, "overraskende": 1, "lovende": 3,
    "anbefaler": 2, "anbefaling": 2, "køb": 1, "opjusterer": 3,
    "opjustering": 3, "opgradering": 2, "optur": 3,
    "glæde": 3, "glad": 3, "begejstret": 4, "begejstring": 4,
    "hurra": 4, "fejre": 3, "festlig": 2,
    "interessant": 2, "spændende": 3, "fantastiske": 4,
    "fornuftigt": 2, "fornuftig": 2, "klog": 2, "smart": 2,
    "forbedring": 2, "forbedret": 2, "forbedre": 2,
    "innovation": 2, "innovativ": 2, "nyskabende": 3,
    "fortjeneste": 2, "velstand": 3, "rigdom": 2,
    "favorit": 2, "elsker": 3, "yndlings": 2,
    "effektiv": 2, "effektivt": 2, "produktiv": 2,
    "vindere": 2, "vinder": 2, "sejr": 3,
    "håb": 2, "håber": 2, "håbefuld": 2,
    "momentum": 1, "fremdrift": 2,

    # Negative words
    "dårlig": -3, "dårligt": -3, "dårlige": -3,
    "negativ": -2, "negativt": -2, "negative": -2,
    "fald": -2, "falder": -2, "faldet": -2, "faldende": -2,
    "tab": -2, "taber": -2, "tabt": -2,
    "krise": -3, "krisen": -3, "kriser": -3,
    "krak": -4, "kollaps": -4, "sammenbrud": -4,
    "recession": -3, "lavkonjunktur": -3, "nedgang": -2,
    "nedtur": -3, "bearish": -2, "bear": -1,
    "risiko": -1, "risikoen": -1, "risikabel": -2, "risikabelt": -2,
    "usikkerhed": -2, "usikker": -2, "usikkert": -2,
    "bekymring": -2, "bekymret": -2, "bekymrende": -2, "bekymringer": -2,
    "frygt": -3, "frygter": -3, "bange": -3, "angst": -3,
    "panik": -4, "kaos": -3, "uro": -2, "ustabil": -2,
    "inflation": -1, "inflationen": -1,
    "rente": 0, "renteforhøjelse": -1, "rentestigning": -1,
    "gæld": -1, "gældssat": -2, "konkurs": -4, "insolvens": -4,
    "tab": -2, "underskud": -2, "deficit": -2,
    "nedgradering": -3, "nedjustering": -3, "nedjusterer": -3,
    "sælg": -1, "sælger": -1, "salg": 0,
    "advarsel": -2, "advarer": -2, "advarsel": -2,
    "problem": -2, "problemer": -2, "udfordring": -1, "udfordringer": -1,
    "svag": -2, "svagt": -2, "svaghed": -2, "svækket": -2,
    "miste": -2, "mistet": -2, "mister": -2,
    "katastrofe": -4, "katastrofal": -4, "forfærdelig": -4,
    "skuffelse": -3, "skuffende": -3, "skuffet": -3,
    "trussel": -3, "trusler": -3, "truet": -2,
    "skandale": -3, "svindel": -4, "bedrag": -4, "bedrageri": -4,
    "manipulation": -3, "korruption": -4,
    "volatilitet": -1, "volatil": -1, "turbulent": -2, "turbulens": -2,
    "boble": -2, "boblen": -2,
    "straf": -2, "bøde": -2, "sanktion": -2, "sanktioner": -2,
    "krig": -3, "krigsfare": -4, "konflikt": -2, "konflikter": -2,
    "pandemi": -3, "epidemi": -3, "lockdown": -2,
    "arbejdsløshed": -2, "fyring": -2, "fyringer": -3, "afskedigelse": -3,
    "tragisk": -4, "sorg": -4, "trist": -3,
    "vrede": -3, "rasende": -4, "frustreret": -3, "frustration": -3,
    "håbløs": -4, "desperat": -3, "opgivelse": -3,
    "dødsfald": -3, "død": -3,
    "umulig": -2, "umuligt": -2,
    "fejl": -2, "fejlslagen": -3,
    "sårbar": -2, "sårbart": -2,
    "pres": -1, "presset": -1, "pression": -2,
    "smerte": -3, "skade": -2, "skader": -2,
    "rædsel": -4, "forfærdende": -4,
    "skræmmende": -3, "uhyggelig": -3,
    "dyster": -3, "dystert": -3, "mørk": -2, "mørkt": -2,

    # Neutral/context words with mild sentiment
    "marked": 0, "markedet": 0, "aktie": 0, "aktier": 0,
    "investering": 0, "investor": 0, "investorer": 0,
    "portefølje": 0, "diversificering": 1,
    "analyse": 0, "analyserer": 0, "vurdering": 0,
    "strategi": 0, "taktik": 0,
    "ændring": 0, "ændringer": 0, "forandring": 0,
    "overvejer": 0, "overvejelse": 0,
    "forsigtig": -1, "forsigtigt": -1, "afdæmpet": -1,
    "afventende": 0, "neutral": 0,
}

# Discrete emotion word lists for Danish (financial/podcast context)
EMOTION_LEXICON: dict[str, list[str]] = {
    "joy": [
        "glæde", "glad", "glade", "lykkelig", "lykke", "begejstret", "begejstring",
        "fantastisk", "fremragende", "vidunderlig", "strålende", "hurra", "fejre",
        "fejring", "succes", "triumf", "sejr", "vinder", "vindere", "gevinst",
        "rekord", "rekordstort", "rekordhøj", "optur", "boom", "rally",
        "elsker", "favorit", "perfekt", "imponerende", "enestående", "suveræn",
        "optimisme", "optimistisk", "fremgang", "vækst", "overskud", "profit",
        "fortjeneste", "velstand", "anbefaler", "opjustering", "opjusterer",
        "spændende", "fantastiske", "bedste", "god", "godt", "gode",
        "positiv", "positivt", "festlig", "forbedring", "forbedret",
    ],
    "trust": [
        "tillid", "troværdig", "troværdigt", "solid", "robust", "stabil",
        "stabilitet", "sikker", "sikkert", "sikkerhed", "pålidelig", "garanti",
        "garanterer", "forsikring", "beskyttelse", "bæredygtig", "ansvarlig",
        "erfaren", "ekspert", "professionel", "kvalitet", "veletableret",
        "pålideligt", "fornuftig", "fornuftigt", "klog", "diversificering",
        "balance", "afdækning", "hedging", "langsigtet", "strategi",
        "fundamental", "fundamentalt", "analyse", "gennemprøvet",
    ],
    "anticipation": [
        "forventer", "forventning", "forventninger", "spændt", "spænding",
        "håb", "håber", "håbefuld", "fremtid", "fremtiden", "potentiale",
        "mulighed", "muligheder", "chance", "kommende", "snart", "planlægger",
        "plan", "mål", "ambition", "ambitiøs", "vision", "prognose",
        "forecast", "udsigt", "udsigter", "venter", "afventer", "forberedelse",
        "forberedt", "næste", "innovation", "innovativ", "nyskabende",
        "momentum", "fremdrift", "lovende", "trend", "tendens",
    ],
    "surprise": [
        "overraskende", "overraskelse", "overrasket", "uventet", "pludselig",
        "chok", "chokerende", "utrolig", "utroligt", "uforudset", "dramatisk",
        "exceptionel", "usædvanlig", "bemærkelsesværdig", "sensationel",
        "historisk", "hidtil", "uset", "aldrig", "rekord", "vendepunkt",
        "banebrydende", "revolution", "revolutionerende", "omvæltning",
    ],
    "fear": [
        "frygt", "frygter", "bange", "angst", "bekymring", "bekymret",
        "bekymrende", "bekymringer", "risiko", "risikoen", "risikabel",
        "usikkerhed", "usikker", "panik", "rædsel", "skræmmende", "uhyggelig",
        "trussel", "trusler", "truet", "fare", "farlig", "alarmerende",
        "krise", "krisen", "katastrofe", "katastrofal", "kaos",
        "volatilitet", "volatil", "turbulens", "turbulent", "ustabil",
        "sårbar", "desperat", "nervøs", "uro", "boble", "boblen",
        "krak", "kollaps", "sammenbrud", "recession", "pandemi",
        "krig", "krigsfare", "konflikt", "lockdown",
    ],
    "sadness": [
        "trist", "sorg", "tragisk", "skuffelse", "skuffende", "skuffet",
        "tab", "taber", "tabt", "miste", "mistet", "mister", "nedgang",
        "nedtur", "dårlig", "dårligt", "dårlige", "håbløs", "opgivelse",
        "fald", "faldet", "faldende", "svag", "svagt", "svaghed", "svækket",
        "underskud", "deficit", "konkurs", "insolvens", "fyring", "fyringer",
        "afskedigelse", "arbejdsløshed", "dødsfald", "smerte",
        "nedjustering", "nedjusterer", "nedgradering", "dyster", "dystert",
        "mørk", "mørkt", "fejl", "fejlslagen",
    ],
    "anger": [
        "vrede", "rasende", "frustreret", "frustration", "irritation",
        "irriteret", "harme", "forargelse", "forarget", "oprørt", "empørt",
        "skandale", "svindel", "bedrag", "bedrageri", "manipulation",
        "korruption", "uretfærdig", "uretfærdigt", "snyd", "snydt",
        "straf", "bøde", "sanktion", "sanktioner", "protest", "protester",
        "krav", "kritik", "kritiserer", "anklage", "anklager",
        "uacceptabel", "uacceptabelt", "utilfreds", "utilfredshed",
        "forbitret", "forbandelse", "had", "fjendtlig",
    ],
    "disgust": [
        "afsky", "frastødende", "modbydelig", "væmmelig", "kvalm",
        "korruption", "svindel", "bedrag", "bedrageri", "grådighed",
        "grådig", "uansvarlig", "uansvarligt", "skamfuld", "skam",
        "skandaløs", "uetisk", "umoralsk", "forkastelig", "foragtelig",
        "misbruge", "misbrug", "udnyttelse", "udnytter",
        "grotesk", "absurd", "hykleri", "dobbeltmoral",
    ],
}
